---
# yaml-language-server: $schema=https://kubernetes-schemas.pages.dev/source.toolkit.fluxcd.io/ocirepository_v1beta2.json
apiVersion: source.toolkit.fluxcd.io/v1beta2
kind: OCIRepository
metadata:
  name: confluence
spec:
  interval: 5m
  layerSelector:
    mediaType: application/vnd.cncf.helm.chart.content.v1.tar+gzip
    operation: copy
  ref:
    tag: 1.22.7
  url: oci://ghcr.io/astrateam-net/oci-charts/confluence
  verify:
    provider: cosign
    matchOIDCIdentity:
      - issuer: "^https://token.actions.githubusercontent.com$"
        subject: "^https://github.com/astrateam-net/oci-charts.*$"
---
# yaml-language-server: $schema=https://kubernetes-schemas.pages.dev/helm.toolkit.fluxcd.io/helmrelease_v2.json
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: confluence
spec:
  interval: 1h
  chartRef:
    kind: OCIRepository
    name: confluence
  install:
    remediation:
      retries: -1
  upgrade:
    cleanupOnFail: true
    remediation:
      retries: 3
  values:
    fullnameOverride: confluence
    replicaCount: 1
    image:
      repository: astraautoio/astrawiki
      pullPolicy: IfNotPresent
      tag: "9.3.2"
    database:
      type: postgresql
      url: "jdbc:postgresql://10.1.125.55:5000/confluencedb"
      # driver: org.postgresql.Driver
      credentials:
        secretName: confdb-credentials-secret
        usernameSecretKey: CONFLUENCE_DB_USER
        passwordSecretKey: CONFLUENCE_DB_PASSWORD
    volumes:
      localHome:
        persistentVolumeClaim:
          create: true
          storageClassName: ceph-block
          resources:
            requests:
              storage: 10Gi
      sharedHome:
        persistentVolumeClaim:
          create: true
          accessModes:
            - ReadWriteOnce
          storageClassName: ceph-block
          resources:
            requests:
              storage: 30Gi
      synchronyHome:
        persistentVolumeClaim:
          create: true
          storageClassName: ceph-block
          resources:
            requests:
              storage: 2Gi
    confluence:
      useHelmReleaseNameAsContainerName: false
      readinessProbe:
        enabled: true
      s3AttachmentsStorage:
        bucketName:
        bucketRegion:
        endpointOverride:
      additionalJvmArgs:
        - "-Dupm.plugin.upload.enabled=true"
    synchrony:
      enabled: true
    opensearch:
      enabled: true
      persistence:
        storageClass: ceph-block
        size: 10Gi
